---

# - include: config.yml
#   when: sonar_config

# - include: analyzer_runner.yml
#   when: sonar_analyzer_runner_install

# - include: plugins.yml

# - include: maven.yml
#   when: maven_install

 - include: users.yml
   when: sonar_users is defined

 - include: groups.yml
   when: sonar_groups is defined

 - include: permissions.yml
   when: permission_templates is defined

# - include: projects.yml
#   when: sonar_projects is defined
